name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: list dir
        run: dir
        
      - name: Get version
        id: getversion
        run: echo "::set-output name=v::$(node -p "require('./package.json').version")"
        
      - name: Display version
        run: echo ${{ steps.getversion.outputs.v }}

      - name: Install modules
        run: npm i
        
      - name: Make build dir
        run: mkdir build
        
      - name: Build windows binary
        run: npm run dist
        
      - name: package to zip
        uses: papeloto/action-zip@v1
        with:
          files: ./build/win-unpacked
          dest: ./build/streamer-tools-client.zip
        
      - name: Upload windows binary
        uses: actions/upload-artifact@v2
        with:
          name: streamer-tools-client_win.zip
          path: ./build/streamer-tools-client.zip
          if-no-files-found: error
